const Discord = require('discord.js');
const unirest = require("unirest");

module.exports = {
     name: "lol",
     description: "Permet de voir les ranks de vos adversaires",
     usage: "lol pseudo",
    run: async (client, message, args) => {
        if (args[0] != '') {
            const nom = args.join(' ');
            let getSumId = async () => {
                
                let response = await unirest.get("https://euw1.api.riotgames.com/lol/summoner/v4/summoners/by-name/" + nom)
                    .header("X-Riot-Token", "RGAPI-cebf094b-4de8-4fd2-9f11-a1f392b2ff1f");
                let sumId = response.body;
                try {
                    return sumId.id;
                }
                catch (e) {
                    message.channel.send("Summoner non trouvé");
                }
            }
            let getParticipantsIdTeamBlue = async () => {
                let sumId = await getSumId();
                if (sumId) {
                    let response = await unirest.get("https://euw1.api.riotgames.com/lol/spectator/v4/active-games/by-summoner/" + sumId)
                        .header("X-Riot-Token", "RGAPI-cebf094b-4de8-4fd2-9f11-a1f392b2ff1f");
                
                    let match = response.body;
                    return match.participants;
                }
            }

            let getParticipantsIdTeamRed = async () => {
                let sumId = await getSumId();
                if (sumId) {
                    let response = await unirest.get("https://euw1.api.riotgames.com/lol/spectator/v4/active-games/by-summoner/" + sumId)
                        .header("X-Riot-Token", "RGAPI-cebf094b-4de8-4fd2-9f11-a1f392b2ff1f");

                    var match = response.body;

                    var matchParsed = JSON.parse(JSON.stringify(match));

                    var participantsRed = [];

                    for (var id in matchParsed) {
                        if (matchParsed[id].team == 100) {
                            participantsRed.push(matchParsed[id]);
                            
                        }
                    }
                    return match.participants;
                }

            }

        
            
            let getSumRank = async () => {
                let participants = await getParticipantsIdTeamRed();

                var participantsIds = [];
                for (var id in participants) {
                    let response = await unirest.get("https://euw1.api.riotgames.com/lol/league/v4/entries/by-summoner/" + participants[id].summonerId)
                        .header("X-Riot-Token", "RGAPI-cebf094b-4de8-4fd2-9f11-a1f392b2ff1f");
                    
                    for (var e in response.body) {
                        if (response.body[e].queueType === "RANKED_SOLO_5x5") {
                            participantsIds.push(response.body[e].tier + ' ' + response.body[e].rank + '\n' + response.body[e].leaguePoints + ' LP');
                        }
                    }
                }
                return participantsIds;
            }

            let getSumNames = async () => {
                let participants = await getParticipantsIdTeamRed();

                var participantsNames = [];
                for (var id in participants) {
                    let response = await unirest.get("https://euw1.api.riotgames.com/lol/league/v4/entries/by-summoner/" + participants[id].summonerId)
                        .header("X-Riot-Token", process.env.TOKEN_RIOT);
                    participantsNames.push(response.body[0].summonerName)
                }
                return participantsNames;
            }

            let sumRanks = await getSumRank();
            let sumNames = await getSumNames();

            if (sumRanks.length>0) {
                

                const URL = 'https://euw.op.gg/summoner/userName=' + args.join('+');
                const embed = new Discord.RichEmbed()
                    .setColor('#ffff00')
                    .setURL(URL)
                    .setTitle('Ranks de la game (en SoloQ) : ')
                    .setFooter("Generated by Riot | Created by Elyth", "https://dotesports-media.nyc3.cdn.digitaloceanspaces.com/wp-content/uploads/2018/12/13175332/riot-logo-black-text.png")
                    .setThumbnail('https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fyt3.ggpht.com%2Fa-%2FAAuE7mBabm11q4VVKRh2xsSoe9f0ArJXSbRkwp2ZSQ%3Ds900-mo-c-c0xffffffff-rj-k-no&f=1&nofb=1');
                
                for (var i = 0; i <= 4; i++) {
                    embed.addBlankField(true)
                    embed.addField(sumNames[i], sumRanks[i], true)
                    embed.addField(sumNames[9 - i], sumRanks[9 - i], true)

                }
                message.channel.send(embed);
            }
            else {
                message.channel.send('Désolé, ' + nom + ' n\'est pas en partie');
            }
        }

    }
}