const Discord = require('discord.js');
const genius = require("genius-lyrics");
const Genius = new genius.Client(process.env.TOKEN_GENIUS);

module.exports = {
    name: "lyrics",
    description: "Renvoi les paroles d'une musique",
    usage: 'lyrics nom',
    run: async (client, message, args) => {

        const search = await Genius.findTrack(JSON.stringify(args));
        const url = await Genius.getUrl(search);
        const lyricsJSON = await Genius.getLyrics(url);
        const lyrics = lyricsJSON.lyrics;
        const all = await Genius.getAll(search);
        const re = /\[[^)]*?\]/g
        const result = lyrics.split(re);
        const reVerse =  /\[(.*?)\]/g
        const verse = lyrics.split(reVerse);

        try {
            const embed = new Discord.RichEmbed()
                .setColor('#ffff00')
                .setTitle("Paroles de " + all.title)
                .setDescription("par " + all.primary_artist.name)
                .setThumbnail(all.song_art_image_thumbnail_url)
                .setURL(url)
                .setFooter("Generated by Genius | Created by Elyth","https://images.genius.com/8ed669cadd956443e29c70361ec4f372.1000x1000x1.png");
            for (let i = 1; i < result.length; i++) {
                embed.addField(verse[i] + i, result[i]);
            }
            message.channel.send(embed);
        } catch (e) {
            const embed = new Discord.RichEmbed()
                .setColor('#ffff00')
                .setTitle("Paroles de " + all.title)
                .setDescription("par " + all.primary_artist.name)
                .setThumbnail(all.song_art_image_thumbnail_url)
                .setURL(url)
                .addField("Paroles trop longues (>2000 mots)", "Vous pouvez retrouver le lien des paroles en cliquant sur le nom de la musique en haut")
                .setFooter("Generated by Genius | Created by Elyth","https://images.genius.com/8ed669cadd956443e29c70361ec4f372.1000x1000x1.png");
            message.channel.send(embed);
        }
    }
}